Repository CSC207-2022F-UofT/course-project-unu, pull requests merged in 2022-12, with the labels that each got.

#37 Csv gateway
  .DS_Store
  .idea/misc.xml
  README.md
  db/stats.csv
  db/test_stats.csv
  src/main/.DS_Store
  src/main/java/gateway/CSVGateway.java
  src/main/java/gateway/CSVHandler.java
  src/main/java/gateway/DBGateway.java
  src/test/java/card_tests/CardEffectTests.java
  src/test/java/card_tests/GeneralCardTests.java
  src/test/java/gateway_tests/CSVGatewayTests.java
Labels: enhancement

#47 3 feature 4 user interface
  src/main/java/UI/ChooseColourPage.java
  src/main/java/UI/GameBoard.java
  src/main/java/UI/PlayCardWindow.java
  src/main/java/UI/RegularModeSetup.java
  src/main/java/UI/StartPage.java
  src/main/java/UI/TeamModeSetup.java
  src/main/java/UI/UIComponent.java
  src/main/java/UI/ViewMethods.java
  src/main/java/interfaceAdapters/Controller.java
Labels: documentation, enhancement

#48 40 game facade
  src/main/java/entities/GameState.java
  src/main/java/interfaceAdapters/Presenter.java
  src/main/java/useCases/ChangeColour.java
  src/main/java/useCases/ChangeDirection.java
  src/main/java/useCases/ChangeTurn.java
  src/main/java/useCases/CheckWin.java
  src/main/java/useCases/DisplayRealPlayerOptions.java
  src/main/java/useCases/Draw.java
  src/main/java/useCases/GameFacade.java
  src/main/java/useCases/GameRecorder.java
  src/main/java/useCases/GameSetup.java
  src/main/java/useCases/LastPlayedEffect.java
  src/main/java/useCases/MakeBotMove.java
  src/main/java/useCases/Play.java
  src/main/java/useCases/StringConverter.java
Labels: enhancement

#53 created result page and finished the documentations of the UI classes
  src/main/java/UI/ChooseColourPage.java
  src/main/java/UI/GameBoard.java
  src/main/java/UI/GameManager.java
  src/main/java/UI/PlayCardWindow.java
  src/main/java/UI/RegularModeSetup.java
  src/main/java/UI/ResultPage.java
  src/main/java/UI/StartPage.java
  src/main/java/UI/UIComponent.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/interfaceAdapters/Controller.java
Labels: documentation, enhancement, help wanted

#58 3 feature 4 user interface
  src/main/java/UI/ResultPage.java
  src/main/java/UI/TeamModeSetup.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
Labels: enhancement

#56 Updated Card Classes to use GameFacade
  src/main/java/cards/Card.java
  src/main/java/cards/NumberCard.java
  src/main/java/cards/PlusFourCard.java
  src/main/java/cards/PlusTwoCard.java
  src/main/java/cards/ReverseCard.java
  src/main/java/cards/SkipCard.java
  src/main/java/cards/WildCard.java
  src/main/java/interfaceAdapters/Controller.java
Labels: enhancement

#60 Rewording cardType documentation
  src/main/java/cards/Card.java
Labels: documentation

#65 added player ranking UI features
  src/main/java/UI/ResultPage.java
  src/main/java/UI/ScoreBoard.java
  src/main/java/UI/UIComponent.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/interfaceAdapters/Controller.java
Labels: enhancement

#62 Implemented PlayerRanking.java, Fixed Bugs in UserProfile and Added test cases
  src/main/java/UserProfilePage/PlayerRanking.java
  src/main/java/UserProfilePage/UserProfile.java
  src/test/java/userprofiletests/UserProfileTests.java
Labels: enhancement

#66 Win losses
  src/main/java/UI/GameManager.java
  src/main/java/UI/ResultPage.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/interfaceAdapters/Presenter.java
Labels: enhancement

#75 Fix excess wildcards
  src/main/java/cards/PlusFourCard.java
  src/main/java/entities/BotPlayer.java
  src/main/java/entities/GameState.java
  src/main/java/useCases/GameFacade.java
Labels: bug

#74 Bugfix branch
  src/main/java/TeamMode/TeamRealPlayer.java
  src/main/java/cards/WildCard.java
  src/test/java/team_mode_tests/TeamTest.java
Labels: enhancement

#77 Fixing warnings.
  src/main/java/TeamMode/Team.java
  src/main/java/TeamMode/TeamBotPlayer.java
  src/main/java/TeamMode/TeamRealPlayer.java
  src/main/java/UI/TeamModeSetup.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/cards/ColourChange_UseCaseInteractor.java
  src/main/java/cards/WildCard.java
  src/main/java/entities/BotPlayer.java
  src/main/java/entities/Player.java
  src/main/java/interfaceAdapters/Controller.java
  src/main/java/interfaceAdapters/Presenter_Interface.java
Labels: documentation

#78 Reorganized packages into clean architecture packages
  db/stats.csv
  src/main/java/UI/GameManager.java
  src/main/java/UI/ResultPage.java
  src/main/java/entities/BotPlayer.java
  src/main/java/entities/CardFactory.java
  src/main/java/entities/GameState.java
  src/main/java/entities/Player.java
  src/main/java/entities/RealPlayer.java
  src/main/java/entities/cards/Card.java
  src/main/java/entities/cards/NumberCard.java
  src/main/java/entities/cards/PlusFourCard.java
  src/main/java/entities/cards/PlusTwoCard.java
  src/main/java/entities/cards/ReverseCard.java
  src/main/java/entities/cards/SkipCard.java
  src/main/java/entities/cards/WildCard.java
  src/main/java/entities/teammode/Team.java
  src/main/java/entities/teammode/TeamBotPlayer.java
  src/main/java/entities/teammode/TeamPlayer.java
  src/main/java/entities/teammode/TeamRealPlayer.java
  src/main/java/interfaceAdapters/Controller.java
  src/main/java/interfaceAdapters/Presenter.java
  src/main/java/interfaceAdapters/gateway/CSVGateway.java
  src/main/java/interfaceAdapters/gateway/CSVHandler.java
  src/main/java/interfaceAdapters/gateway/DBGateway.java
  src/main/java/moves/ComputerMoves.java
  src/main/java/moves/Moves.java
  src/main/java/useCases/DisplayRealPlayerOptions.java
  src/main/java/useCases/Draw.java
  src/main/java/useCases/GameSetup.java
  src/main/java/useCases/LastPlayedEffect.java
  src/main/java/useCases/Play.java
  src/main/java/useCases/StringConverter.java
  src/main/java/useCases/UserProfilePage/PlayerRanking.java
  src/main/java/useCases/UserProfilePage/RecordGame.java
  src/main/java/useCases/UserProfilePage/UserProfile.java
  src/test/java/card_tests/GeneralCardTests.java
  src/test/java/gateway_tests/CSVGatewayTests.java
  src/test/java/move_tests/PossibleMovesTests.java
  src/test/java/player_tests/PlayerTests.java
  src/test/java/team_mode_tests/TeamTest.java
  src/test/java/use_case_tests/GameFacadeTests.java
  src/test/java/userprofiletests/UserProfileTests.java
Labels: enhancement

#81 3 feature 4 user interface
  src/main/java/UI/ResultPage.java
  src/main/java/UI/ScoreBoard.java
  src/main/java/UI/TeamModeSetup.java
  src/main/java/entities/BotPlayer.java
Labels: documentation

#79 Updated Controller and documentation in PlayerRanking.java
  src/main/java/interfaceAdapters/Controller.java
  src/main/java/interfaceAdapters/Presenter.java
  src/main/java/useCases/Presenter_Interface.java
  src/main/java/useCases/UserProfilePage/PlayerRanking.java
Labels: enhancement
