Repository CSC207-2022F-UofT/course-project-unu, pull requests merged in 2022-11, with the labels that each got.

#10 Feature 1 card object development branch
  src/main/java/Game/Game.java
  src/main/java/cards/Card.java
  src/main/java/cards/NumberCard.java
  src/main/java/cards/PlusFourCard.java
  src/main/java/cards/PlusTwoCard.java
  src/main/java/cards/ReverseCard.java
  src/main/java/cards/SkipCard.java
  src/main/java/cards/WildCard.java
Labels: enhancement

#9 Feature 5 player and realplayer
  src/main/java/entities/Player.java
  src/main/java/entities/RealPlayer.java
Labels: enhancement

#13 Feature 1 card object development branch - Part 2
  src/main/java/cards/Card.java
  src/main/java/cards/NumberCard.java
  src/main/java/cards/PlusFourCard.java
  src/main/java/cards/PlusTwoCard.java
  src/main/java/cards/ReverseCard.java
  src/main/java/cards/SkipCard.java
  src/main/java/cards/WildCard.java
Labels: enhancement

#16 Feature 2 move system
  src/main/java/entities/Player.java
  src/main/java/entities/RealPlayer.java
  src/main/java/game/Game.java
  src/main/java/moves/ComputerMoves.java
  src/main/java/moves/Moves.java
Labels: enhancement

#18 8 feature 1 team game
  .idea/.gitignore
  .idea/misc.xml
  .idea/vcs.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/TeamMode/Team.java
  src/main/java/TeamMode/TeamMode.java
  src/main/java/TeamMode/TeamPlayer.java
  src/main/java/UI/GameManager.java
  src/main/java/UI/StartPage.java
  src/main/java/cards/Card.java
  src/main/java/cards/NumberCard.java
  src/main/java/cards/PlusFourCard.java
  src/main/java/cards/PlusTwoCard.java
  src/main/java/cards/ReverseCard.java
  src/main/java/cards/SkipCard.java
  src/main/java/cards/WildCard.java
Labels: enhancement

#15 Feature 1 card object development branch
  src/main/java/cards/Card.java
Labels: documentation

#21 Feature 1 card object development branch
  src/main/java/cards/Card.java
  src/main/java/cards/ChangeColour.java
  src/main/java/cards/ChangeColour_Interface.java
  src/main/java/cards/NumberCard.java
  src/main/java/cards/PlusFourCard.java
  src/main/java/cards/PlusTwoCard.java
  src/main/java/cards/ReverseCard.java
  src/main/java/cards/SkipCard.java
  src/main/java/cards/WildCard.java
Labels: enhancement

#24 Wrote Controller method signatures, created game setup pages and a basic gameboard layout
  src/main/java/UI/ActionHandler.java
  src/main/java/UI/GameBoard.java
  src/main/java/UI/GameManager.java
  src/main/java/UI/PlayCardWindow.java
  src/main/java/UI/RegularModeSetup.java
  src/main/java/UI/StartPage.java
  src/main/java/UI/TeamModeSetup.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/interfaceAdapters/Controller.java
  src/main/resources/RedBot.png
  src/main/resources/StripeBot.png
  src/main/resources/UNO_logo.jpg
  src/main/resources/WhiteBot.png
  src/main/resources/gameBoardBG.png
Labels: enhancement

#26 Feature 2 move system - default moves and makeMove()
  src/main/java/entities/Player.java
  src/main/java/game/Game.java
  src/main/java/moves/Moves.java
Labels: enhancement

#28 Card object tests
  src/test/java/card_tests/CardEffectTests.java
  src/test/java/card_tests/GeneralCardTests.java
Labels: enhancement

#30 Feature 1 card object development branch interface experiments
  src/main/java/UI/GameBoard.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/cards/ColourChange_UseCaseInteractor.java
  src/main/java/cards/WildCard.java
  src/main/java/game/Game.java
  src/main/java/interfaceAdapters/Presenter.java
  src/main/java/interfaceAdapters/Presenter_Interface.java
Labels: enhancement

#22 7 feature user profile system
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  .idea/vcs.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/TeamMode/Team.java
  src/main/java/TeamMode/TeamMode.java
  src/main/java/TeamMode/TeamPlayer.java
  src/main/java/UI/GameBoard.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/UserProfilePage/PlayerRanking.java
  src/main/java/UserProfilePage/RecordGame.java
  src/main/java/UserProfilePage/UserProfile.java
  src/main/java/cards/ColourChange_UseCaseInteractor.java
  src/main/java/cards/WildCard.java
  src/main/java/entities/CardFactory.java
  src/main/java/entities/Player.java
  src/main/java/game/Game.java
  src/main/java/interfaceAdapters/Presenter.java
  src/main/java/interfaceAdapters/Presenter_Interface.java
  src/main/java/moves/Moves.java
  src/test/java/card_tests/CardEffectTests.java
  src/test/java/card_tests/GeneralCardTests.java
Labels: enhancement

#29 8 feature ai
  .idea/misc.xml
  .idea/vcs.xml
  bin/main/bg.jpg
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/cards/Card.java
  src/main/java/cards/NumberCard.java
  src/main/java/cards/PlusFourCard.java
  src/main/java/cards/PlusTwoCard.java
  src/main/java/cards/ReverseCard.java
  src/main/java/cards/SkipCard.java
  src/main/java/cards/WildCard.java
  src/main/java/entities/BotPlayer.java
  src/main/java/game/Game.java
  src/main/java/moves/ComputerMoves.java
Labels: enhancement

#34 Update README file
  README.md
Labels: documentation

#38 3 feature 4 user interface
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  gradlew
  gradlew.bat
  src/main/java/TeamMode/Team.java
  src/main/java/TeamMode/TeamPlayer.java
  src/main/java/UI/ActionHandler.java
  src/main/java/UI/GameBoard.java
  src/main/java/UI/GameManager.java
  src/main/java/UI/RegularModeSetup.java
  src/main/java/UI/StartPage.java
  src/main/java/UI/TeamModeSetup.java
  src/main/java/UI/View.java
  src/main/java/UI/ViewMethods.java
  src/main/java/UserProfilePage/PlayerRanking.java
  src/main/java/UserProfilePage/RecordGame.java
  src/main/java/UserProfilePage/UserProfile.java
  src/main/java/interfaceAdapters/Controller.java
  src/main/resources/CardBackSide.png
Labels: enhancement

#39 8 feature 1 team game 1
  src/main/java/TeamMode/Team.java
  src/main/java/TeamMode/TeamMode.java
  src/main/java/TeamMode/TeamPlayer.java
  src/main/java/interfaceAdapters/Controller.java
Labels: duplicate

#44 Updated documentation of the Card class
  src/main/java/cards/Card.java
Labels: documentation
